# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\gerha\Google Drive\Studies\Unisa\INF2611 - Visual Programming 2\Programs\INF2611_Python_QT\Assignment3\EventMan.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1220, 878)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.mdiArea = QtGui.QMdiArea(self.centralwidget)
        self.mdiArea.setGeometry(QtCore.QRect(0, 0, 1211, 811))
        self.mdiArea.setViewMode(QtGui.QMdiArea.TabbedView)
        self.mdiArea.setTabsClosable(True)
        self.mdiArea.setTabShape(QtGui.QTabWidget.Rounded)
        self.mdiArea.setObjectName(_fromUtf8("mdiArea"))
        self.AddEvent = QtGui.QWidget()
        self.AddEvent.setObjectName(_fromUtf8("AddEvent"))
        self.formLayoutWidget = QtGui.QWidget(self.AddEvent)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 391, 351))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.formLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.eventName = QtGui.QLineEdit(self.formLayoutWidget)
        self.eventName.setObjectName(_fromUtf8("eventName"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.eventName)
        self.label_2 = QtGui.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtGui.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_3)
        self.eventLimit = QtGui.QLineEdit(self.formLayoutWidget)
        self.eventLimit.setObjectName(_fromUtf8("eventLimit"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.eventLimit)
        self.eventDate = QtGui.QCalendarWidget(self.formLayoutWidget)
        self.eventDate.setObjectName(_fromUtf8("eventDate"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.eventDate)
        self.label_4 = QtGui.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_4)
        self.eventStartTime = QtGui.QTimeEdit(self.formLayoutWidget)
        self.eventStartTime.setObjectName(_fromUtf8("eventStartTime"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.eventStartTime)
        self.label_5 = QtGui.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_5)
        self.eventEndTime = QtGui.QTimeEdit(self.formLayoutWidget)
        self.eventEndTime.setObjectName(_fromUtf8("eventEndTime"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.eventEndTime)
        self.label_6 = QtGui.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtGui.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtGui.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_8)
        self.eventFee = QtGui.QLineEdit(self.formLayoutWidget)
        self.eventFee.setObjectName(_fromUtf8("eventFee"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.eventFee)
        self.eventClient = QtGui.QLineEdit(self.formLayoutWidget)
        self.eventClient.setObjectName(_fromUtf8("eventClient"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.eventClient)
        self.eventVenue = QtGui.QLineEdit(self.formLayoutWidget)
        self.eventVenue.setObjectName(_fromUtf8("eventVenue"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.eventVenue)
        self.eventSubmitButton = QtGui.QPushButton(self.AddEvent)
        self.eventSubmitButton.setGeometry(QtCore.QRect(150, 370, 75, 23))
        self.eventSubmitButton.setObjectName(_fromUtf8("eventSubmitButton"))
        self.AddClient = QtGui.QWidget()
        self.AddClient.setObjectName(_fromUtf8("AddClient"))
        self.groupBox_4 = QtGui.QGroupBox(self.AddClient)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 20, 291, 121))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.formLayoutWidget_5 = QtGui.QWidget(self.groupBox_4)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(10, 20, 261, 100))
        self.formLayoutWidget_5.setObjectName(_fromUtf8("formLayoutWidget_5"))
        self.formLayout_5 = QtGui.QFormLayout(self.formLayoutWidget_5)
        self.formLayout_5.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.label_28 = QtGui.QLabel(self.formLayoutWidget_5)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_28)
        self.label_29 = QtGui.QLabel(self.formLayoutWidget_5)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_29)
        self.clientLastName = QtGui.QLineEdit(self.formLayoutWidget_5)
        self.clientLastName.setObjectName(_fromUtf8("clientLastName"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.clientLastName)
        self.clientPhone = QtGui.QLineEdit(self.formLayoutWidget_5)
        self.clientPhone.setObjectName(_fromUtf8("clientPhone"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.FieldRole, self.clientPhone)
        self.label_17 = QtGui.QLabel(self.formLayoutWidget_5)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_17)
        self.clientFirstName = QtGui.QLineEdit(self.formLayoutWidget_5)
        self.clientFirstName.setObjectName(_fromUtf8("clientFirstName"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.clientFirstName)
        self.label_25 = QtGui.QLabel(self.formLayoutWidget_5)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_25)
        self.clientEmail = QtGui.QLineEdit(self.formLayoutWidget_5)
        self.clientEmail.setObjectName(_fromUtf8("clientEmail"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.FieldRole, self.clientEmail)
        self.clientSubmitButton = QtGui.QPushButton(self.AddClient)
        self.clientSubmitButton.setGeometry(QtCore.QRect(100, 140, 75, 23))
        self.clientSubmitButton.setObjectName(_fromUtf8("clientSubmitButton"))
        self.AddVenue = QtGui.QWidget()
        self.AddVenue.setObjectName(_fromUtf8("AddVenue"))
        self.groupBox = QtGui.QGroupBox(self.AddVenue)
        self.groupBox.setGeometry(QtCore.QRect(10, 230, 291, 161))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayoutWidget_3 = QtGui.QWidget(self.groupBox)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 261, 131))
        self.formLayoutWidget_3.setObjectName(_fromUtf8("formLayoutWidget_3"))
        self.formLayout_3 = QtGui.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_21 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_21)
        self.label_22 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_22)
        self.label_23 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_23)
        self.label_24 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_24)
        self.venueAddress = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.venueAddress.setObjectName(_fromUtf8("venueAddress"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.venueAddress)
        self.venueCity = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.venueCity.setObjectName(_fromUtf8("venueCity"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.venueCity)
        self.venueProvince = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.venueProvince.setObjectName(_fromUtf8("venueProvince"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.venueProvince)
        self.venuePostalCode = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.venuePostalCode.setObjectName(_fromUtf8("venuePostalCode"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.venuePostalCode)
        self.groupBox_2 = QtGui.QGroupBox(self.AddVenue)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 20, 291, 91))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.formLayoutWidget_2 = QtGui.QWidget(self.groupBox_2)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 261, 61))
        self.formLayoutWidget_2.setObjectName(_fromUtf8("formLayoutWidget_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_12 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_12)
        self.venueName = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.venueName.setObjectName(_fromUtf8("venueName"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.venueName)
        self.label_18 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_18)
        self.venueCapacity = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.venueCapacity.setObjectName(_fromUtf8("venueCapacity"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.venueCapacity)
        self.groupBox_3 = QtGui.QGroupBox(self.AddVenue)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 110, 291, 121))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.formLayoutWidget_4 = QtGui.QWidget(self.groupBox_3)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(10, 20, 261, 91))
        self.formLayoutWidget_4.setObjectName(_fromUtf8("formLayoutWidget_4"))
        self.formLayout_4 = QtGui.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_26 = QtGui.QLabel(self.formLayoutWidget_4)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_26)
        self.label_27 = QtGui.QLabel(self.formLayoutWidget_4)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_27)
        self.venueContactNumber = QtGui.QLineEdit(self.formLayoutWidget_4)
        self.venueContactNumber.setObjectName(_fromUtf8("venueContactNumber"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.venueContactNumber)
        self.venueContactEmail = QtGui.QLineEdit(self.formLayoutWidget_4)
        self.venueContactEmail.setObjectName(_fromUtf8("venueContactEmail"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.venueContactEmail)
        self.label_16 = QtGui.QLabel(self.formLayoutWidget_4)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_16)
        self.venueContactName = QtGui.QLineEdit(self.formLayoutWidget_4)
        self.venueContactName.setObjectName(_fromUtf8("venueContactName"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.venueContactName)
        self.venueSubmitButton = QtGui.QPushButton(self.AddVenue)
        self.venueSubmitButton.setGeometry(QtCore.QRect(110, 390, 75, 23))
        self.venueSubmitButton.setObjectName(_fromUtf8("venueSubmitButton"))
        self.ViewAllEvents = QtGui.QWidget()
        self.ViewAllEvents.setObjectName(_fromUtf8("ViewAllEvents"))
        self.eventTableWidget = QtGui.QTableWidget(self.ViewAllEvents)
        self.eventTableWidget.setGeometry(QtCore.QRect(0, 0, 851, 771))
        self.eventTableWidget.setRowCount(50)
        self.eventTableWidget.setColumnCount(8)
        self.eventTableWidget.setObjectName(_fromUtf8("eventTableWidget"))
        self.ViewAllClients = QtGui.QWidget()
        self.ViewAllClients.setObjectName(_fromUtf8("ViewAllClients"))
        self.clientTableWidget = QtGui.QTableWidget(self.ViewAllClients)
        self.clientTableWidget.setGeometry(QtCore.QRect(10, 0, 441, 771))
        self.clientTableWidget.setRowCount(50)
        self.clientTableWidget.setColumnCount(4)
        self.clientTableWidget.setObjectName(_fromUtf8("clientTableWidget"))
        self.ViewAllVenues = QtGui.QWidget()
        self.ViewAllVenues.setObjectName(_fromUtf8("ViewAllVenues"))
        self.venueTableWidget = QtGui.QTableWidget(self.ViewAllVenues)
        self.venueTableWidget.setGeometry(QtCore.QRect(0, 0, 951, 771))
        self.venueTableWidget.setRowCount(50)
        self.venueTableWidget.setColumnCount(9)
        self.venueTableWidget.setObjectName(_fromUtf8("venueTableWidget"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1220, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionAdd_Event = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/newevent.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdd_Event.setIcon(icon)
        self.actionAdd_Event.setObjectName(_fromUtf8("actionAdd_Event"))
        self.actionNew_Client = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/newclient.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew_Client.setIcon(icon1)
        self.actionNew_Client.setObjectName(_fromUtf8("actionNew_Client"))
        self.actionNew_Venue = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/newvenue.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew_Venue.setIcon(icon2)
        self.actionNew_Venue.setObjectName(_fromUtf8("actionNew_Venue"))
        self.actionAll_Events = QtGui.QAction(MainWindow)
        self.actionAll_Events.setObjectName(_fromUtf8("actionAll_Events"))
        self.actionAll_Clients = QtGui.QAction(MainWindow)
        self.actionAll_Clients.setObjectName(_fromUtf8("actionAll_Clients"))
        self.actionAll_Venues = QtGui.QAction(MainWindow)
        self.actionAll_Venues.setObjectName(_fromUtf8("actionAll_Venues"))
        self.menuView.addAction(self.actionAll_Events)
        self.menuView.addAction(self.actionAll_Clients)
        self.menuView.addAction(self.actionAll_Venues)
        self.menubar.addAction(self.menuView.menuAction())
        self.toolBar.addAction(self.actionAdd_Event)
        self.toolBar.addAction(self.actionNew_Client)
        self.toolBar.addAction(self.actionNew_Venue)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.AddEvent.setWindowTitle(_translate("MainWindow", "Add Event", None))
        self.label.setText(_translate("MainWindow", "Event name", None))
        self.label_2.setText(_translate("MainWindow", "Event Date", None))
        self.label_3.setText(_translate("MainWindow", "Event Limit", None))
        self.label_4.setText(_translate("MainWindow", "Start Time", None))
        self.label_5.setText(_translate("MainWindow", "End Time", None))
        self.label_6.setText(_translate("MainWindow", "Client", None))
        self.label_7.setText(_translate("MainWindow", "Venue", None))
        self.label_8.setText(_translate("MainWindow", "Entrance Fee", None))
        self.eventSubmitButton.setText(_translate("MainWindow", "Submit", None))
        self.AddClient.setWindowTitle(_translate("MainWindow", "Add Client", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Client Detail", None))
        self.label_28.setText(_translate("MainWindow", "First Name", None))
        self.label_29.setText(_translate("MainWindow", "Last name", None))
        self.label_17.setText(_translate("MainWindow", "Phone", None))
        self.label_25.setText(_translate("MainWindow", "Email", None))
        self.clientSubmitButton.setText(_translate("MainWindow", "Submit", None))
        self.AddVenue.setWindowTitle(_translate("MainWindow", "Add Venue", None))
        self.groupBox.setTitle(_translate("MainWindow", "Address", None))
        self.label_21.setText(_translate("MainWindow", "Address", None))
        self.label_22.setText(_translate("MainWindow", "City / Town", None))
        self.label_23.setText(_translate("MainWindow", "Province", None))
        self.label_24.setText(_translate("MainWindow", "Postal Code", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Venue Detail", None))
        self.label_12.setText(_translate("MainWindow", "Venue Name", None))
        self.label_18.setText(_translate("MainWindow", "Capacity", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Contact Detail", None))
        self.label_26.setText(_translate("MainWindow", "Contact name", None))
        self.label_27.setText(_translate("MainWindow", "Contact Number", None))
        self.label_16.setText(_translate("MainWindow", "Email", None))
        self.venueSubmitButton.setText(_translate("MainWindow", "Submit", None))
        self.ViewAllEvents.setWindowTitle(_translate("MainWindow", "All Events", None))
        self.ViewAllClients.setWindowTitle(_translate("MainWindow", "All Clients", None))
        self.ViewAllVenues.setWindowTitle(_translate("MainWindow", "All Venues", None))
        self.menuView.setTitle(_translate("MainWindow", "View", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionAdd_Event.setText(_translate("MainWindow", "Add Event", None))
        self.actionAdd_Event.setToolTip(_translate("MainWindow", "Add Event", None))
        self.actionNew_Client.setText(_translate("MainWindow", "New Client", None))
        self.actionNew_Client.setToolTip(_translate("MainWindow", "New Client", None))
        self.actionNew_Venue.setText(_translate("MainWindow", "New Venue", None))
        self.actionNew_Venue.setToolTip(_translate("MainWindow", "New Venue", None))
        self.actionAll_Events.setText(_translate("MainWindow", "All Events", None))
        self.actionAll_Clients.setText(_translate("MainWindow", "All Clients", None))
        self.actionAll_Venues.setText(_translate("MainWindow", "All Venues", None))

import iconresource_rc
