# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\gerha\Google Drive\Studies\Unisa\INF2611 - Visual Programming 2\Programs\INF2611_Python_QT\Assignment3\EventMan.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1220, 878)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.mdiArea = QtGui.QMdiArea(self.centralwidget)
        self.mdiArea.setGeometry(QtCore.QRect(0, 0, 1211, 811))
        self.mdiArea.setViewMode(QtGui.QMdiArea.TabbedView)
        self.mdiArea.setTabsClosable(True)
        self.mdiArea.setTabShape(QtGui.QTabWidget.Rounded)
        self.mdiArea.setObjectName(_fromUtf8("mdiArea"))
        self.AddEvent = QtGui.QWidget()
        self.AddEvent.setObjectName(_fromUtf8("AddEvent"))
        self.formLayoutWidget = QtGui.QWidget(self.AddEvent)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 352, 339))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.formLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit)
        self.label_2 = QtGui.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtGui.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_2 = QtGui.QLineEdit(self.formLayoutWidget)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEdit_2)
        self.calendarWidget = QtGui.QCalendarWidget(self.formLayoutWidget)
        self.calendarWidget.setObjectName(_fromUtf8("calendarWidget"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.calendarWidget)
        self.label_4 = QtGui.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_4)
        self.timeEdit = QtGui.QTimeEdit(self.formLayoutWidget)
        self.timeEdit.setObjectName(_fromUtf8("timeEdit"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.timeEdit)
        self.label_5 = QtGui.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_5)
        self.timeEdit_2 = QtGui.QTimeEdit(self.formLayoutWidget)
        self.timeEdit_2.setObjectName(_fromUtf8("timeEdit_2"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.timeEdit_2)
        self.label_6 = QtGui.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6)
        self.comboBox = QtGui.QComboBox(self.formLayoutWidget)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.comboBox)
        self.label_7 = QtGui.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_7)
        self.comboBox_2 = QtGui.QComboBox(self.formLayoutWidget)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.comboBox_2)
        self.label_8 = QtGui.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_8)
        self.lineEdit_3 = QtGui.QLineEdit(self.formLayoutWidget)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_3)
        self.AddClient = QtGui.QWidget()
        self.AddClient.setObjectName(_fromUtf8("AddClient"))
        self.label_9 = QtGui.QLabel(self.AddClient)
        self.label_9.setGeometry(QtCore.QRect(60, 80, 46, 13))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.AddVenue = QtGui.QWidget()
        self.AddVenue.setObjectName(_fromUtf8("AddVenue"))
        self.label_12 = QtGui.QLabel(self.AddVenue)
        self.label_12.setGeometry(QtCore.QRect(80, 170, 46, 13))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.ViewAllEvents = QtGui.QWidget()
        self.ViewAllEvents.setObjectName(_fromUtf8("ViewAllEvents"))
        self.label_13 = QtGui.QLabel(self.ViewAllEvents)
        self.label_13.setGeometry(QtCore.QRect(50, 70, 46, 13))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.ViewAllClients = QtGui.QWidget()
        self.ViewAllClients.setObjectName(_fromUtf8("ViewAllClients"))
        self.label_11 = QtGui.QLabel(self.ViewAllClients)
        self.label_11.setGeometry(QtCore.QRect(50, 30, 46, 13))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.ViewAllVenues = QtGui.QWidget()
        self.ViewAllVenues.setObjectName(_fromUtf8("ViewAllVenues"))
        self.label_10 = QtGui.QLabel(self.ViewAllVenues)
        self.label_10.setGeometry(QtCore.QRect(110, 20, 46, 13))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1220, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionAdd_Event = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/newevent.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdd_Event.setIcon(icon)
        self.actionAdd_Event.setObjectName(_fromUtf8("actionAdd_Event"))
        self.actionNew_Client = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/newclient.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew_Client.setIcon(icon1)
        self.actionNew_Client.setObjectName(_fromUtf8("actionNew_Client"))
        self.actionNew_Venue = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/newvenue.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew_Venue.setIcon(icon2)
        self.actionNew_Venue.setObjectName(_fromUtf8("actionNew_Venue"))
        self.actionAll_Events = QtGui.QAction(MainWindow)
        self.actionAll_Events.setObjectName(_fromUtf8("actionAll_Events"))
        self.actionAll_Clients = QtGui.QAction(MainWindow)
        self.actionAll_Clients.setObjectName(_fromUtf8("actionAll_Clients"))
        self.actionAll_Venues = QtGui.QAction(MainWindow)
        self.actionAll_Venues.setObjectName(_fromUtf8("actionAll_Venues"))
        self.menuView.addAction(self.actionAll_Events)
        self.menuView.addAction(self.actionAll_Clients)
        self.menuView.addAction(self.actionAll_Venues)
        self.menubar.addAction(self.menuView.menuAction())
        self.toolBar.addAction(self.actionAdd_Event)
        self.toolBar.addAction(self.actionNew_Client)
        self.toolBar.addAction(self.actionNew_Venue)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.AddEvent.setWindowTitle(_translate("MainWindow", "Add Event", None))
        self.label.setText(_translate("MainWindow", "Event name", None))
        self.label_2.setText(_translate("MainWindow", "Event Date", None))
        self.label_3.setText(_translate("MainWindow", "Event Limit", None))
        self.label_4.setText(_translate("MainWindow", "Start Time", None))
        self.label_5.setText(_translate("MainWindow", "End Time", None))
        self.label_6.setText(_translate("MainWindow", "Client", None))
        self.label_7.setText(_translate("MainWindow", "Venue", None))
        self.label_8.setText(_translate("MainWindow", "Entrance Fee", None))
        self.AddClient.setWindowTitle(_translate("MainWindow", "Add Client", None))
        self.label_9.setText(_translate("MainWindow", "TextLabel", None))
        self.AddVenue.setWindowTitle(_translate("MainWindow", "Add Venue", None))
        self.label_12.setText(_translate("MainWindow", "TextLabel", None))
        self.ViewAllEvents.setWindowTitle(_translate("MainWindow", "All Events", None))
        self.label_13.setText(_translate("MainWindow", "TextLabel", None))
        self.ViewAllClients.setWindowTitle(_translate("MainWindow", "All Clients", None))
        self.label_11.setText(_translate("MainWindow", "TextLabel", None))
        self.ViewAllVenues.setWindowTitle(_translate("MainWindow", "All Venues", None))
        self.label_10.setText(_translate("MainWindow", "TextLabel", None))
        self.menuView.setTitle(_translate("MainWindow", "View", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionAdd_Event.setText(_translate("MainWindow", "Add Event", None))
        self.actionAdd_Event.setToolTip(_translate("MainWindow", "Add Event", None))
        self.actionNew_Client.setText(_translate("MainWindow", "New Client", None))
        self.actionNew_Client.setToolTip(_translate("MainWindow", "New Client", None))
        self.actionNew_Venue.setText(_translate("MainWindow", "New Venue", None))
        self.actionNew_Venue.setToolTip(_translate("MainWindow", "New Venue", None))
        self.actionAll_Events.setText(_translate("MainWindow", "All Events", None))
        self.actionAll_Clients.setText(_translate("MainWindow", "All Clients", None))
        self.actionAll_Venues.setText(_translate("MainWindow", "All Venues", None))

import iconresource_rc
